CREATE database QUANLYNHAHANG
GO

USE QUANLYNHAHANG
GO

-- FOOD 
-- TABLE
-- FOODCATERY
-- ACCOUNT
-- BILL
-- BILLINFO
CREATE TABLE TABLEfood
(
	ID INT IDENTITY  PRIMARY KEY,
	NAME NVARCHAR(30) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN',
	STATUS NVARCHAR(30) NOT NULL DEFAULT N'Trống' -- TRỐNG HOẶC CÓ NGƯỜI
)
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(50) PRIMARY KEY,
	PASSWORD VARCHAR(100) NOT NULL  DEFAULT 1111,
	FULLNAME NVARCHAR(50) NOT NULL,
	TYPE INT NOT NULL DEFAULT 0,-- 1 LÀ ADMIN, O LÀ USER THƯỜNG
	AVT VARCHAR(1000)
)
GO

CREATE TABLE FOODCATERY
(	
	ID INT IDENTITY  PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL  DEFAULT N'CHƯA ĐẶT TÊN'
)
GO

CREATE TABLE FOOD
(	
	ID INT IDENTITY  PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN',
	IDCATERY INT NOT NULL,
	GIA FLOAT NOT NULL  DEFAULT 0,
	FOREIGN KEY(IDCATERY) REFERENCES DBO.FOODCATERY(ID)
)
GO

CREATE TABLE BILL
(
	ID INT IDENTITY  PRIMARY KEY,
	DATECHECKIN DATETIME NOT NULL DEFAULT GETDATE(),
	DATECHECKOUT DATETIME,
	IDTABLE INT  NOT NULL,
	STATUS INT NOT NULL DEFAULT 0, -- 1 ĐÃ THANH TOÁN, 0 CHƯA
	GIAMGIA INT NOT NULL DEFAULT 0,
	FOREIGN KEY(IDTABLE) REFERENCES DBO.TABLEFOOD(ID)
)
GO

CREATE TABLE BILLINFO
(
	ID INT IDENTITY  PRIMARY KEY,
	IDBILL INT NOT NULL,
	IDFOOD INT NOT NULL,
	COUNT INT NOT NULL DEFAULT 0,
	FOREIGN KEY(IDBILL) REFERENCES DBO.BILL(ID),
	FOREIGN KEY(IDFOOD) REFERENCES DBO.FOOD(ID)

)
GO

INSERT INTO ACCOUNT(USERNAME,PASSWORD,FULLNAME,TYPE,AVT)
VALUES(N'phanhai',N'hai123',N'Vũ Văn Hải',0,NULL)


GO

-- THỦ TỤC LẤY ACC TỪ USERNAME
CREATE proc USP_GETACCOUNTLIST(
	@USERNAME VARCHAR(30)
)
AS BEGIN
	SELECT * FROM DBO.ACCOUNT WHERE USERNAME = @USERNAME
END
GO

-- THỦ TỤC ĐĂNG NHẬP
CREATE proc USP_Login
(
	@username varchar(100),
	@password varchar(100)
)
AS 
BEGIN
	SELECT * FROM dbo.ACCOUNT 
	WHERE USERNAME = @username AND PASSWORD = @password
END
GO

-- thêm bàn bằng hàm
DECLARE @i int = 1
WHILE @i <=12
BEGIN
	INSERT dbo.TABLEfood(NAME)
	VALUES(N'Bàn '+ CAST(@i as nvarchar(10))) -- do i kiểu int , không cùng với kiểu với cột NAME: nvarchar, nên tiến hành ép kiểu
	SET @i = @i +1
END
GO

--UPDATE dbo.TABLEfood set STATUS =N'CÓ KHÁCH' WHERE ID =5

-- LẤY DANH SÁCH BÀN 
CREATE proc USP_GetTableList
AS
BEGIN
	 SELECT * FROM dbo.TABLEfood
END
GO

EXEC USP_GetTableList
GO


-- THÊM VÀO FOODCATERY
insert dbo.FOODCATERY(NAME)
values(N'Hải sản')
go

insert dbo.FOODCATERY(NAME)
values(N'Đặc sản ')
go

insert dbo.FOODCATERY(NAME)
values(N'Đồ uống Có cồn')
go

insert dbo.FOODCATERY(NAME)
values(N'Đồ uống giải khát')
go

-- THÊM VÀO BẢNG FOOD
-- THÊM HẢI SẢN
insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'MỰC HẤP',1,150000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'TÔM HÙM HẤP BIA',1,300000)
GO
-- THÊM ĐẶC SẢN RỪNG
insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'LỢN RỪNG XÀO XẢ',2,150000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'CÁ SUỐI NƯỚNG',2,150000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'THỊT TRÂU GÁC BẾP',2,250000)
GO

--THÊM ĐỒ UỐNG CÓ CỒN
insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'VANG PHÁP',3,2000000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'NAPONEOL',3,10000000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'CHIVAS 18',3,9000000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'VOTCA',3,90000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'RƯỢU NẾP',3,60000)
GO

-- THÊM ĐỒ GIẢI KHÁT
insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'CAM VẮT',4,30000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'SINH TỐ XOÀI',4,40000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'SINH TỐ DƯA HẤU',4,40000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'RED BUL',4,30000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'CAFE',4,30000)
GO

insert dbo.FOOD(NAME, IDCATERY, GIA)
values(N'NƯỚC SUỐI',4,10000)
GO

-- THÊM BILL
-- STATUS: 1 ĐÃ CHECKOUT

INSERT DBO.BILL(DATECHECKIN, DATECHECKOUT,IDTABLE, STATUS)
VALUES(GETDATE(), GETDATE(),1,1)
GO

INSERT DBO.BILL(DATECHECKIN, DATECHECKOUT,IDTABLE, STATUS)
VALUES(GETDATE(),NULL,5,0)
GO

INSERT DBO.BILL(DATECHECKIN, DATECHECKOUT,IDTABLE, STATUS)
VALUES(GETDATE(), GETDATE(),7,1)
GO

-- THÊM BILLINFO
 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(4,1,2)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(4,4,2)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(4,3,1)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(5,1,3)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(5,4,1)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(5,5,1)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(6,1,1)
 GO

 INSERT DBO.BILLINFO(IDBILL, IDFOOD,COUNT)
 VALUES(6,3,1)
 GO


 -- Tạo proc thêm Hóa Đơn
 CREATE proc USP_InsertBill
 (	
	@IDTABLE int
 )
 AS 
 BEGIN
	insert dbo.BILL(DATECHECKIN, DATECHECKOUT,IDTABLE,STATUS,GIAMGIA)
	values(GETDATE(),NULL,@IDTABLE,0,0)
END
GO

 -- thêm BillInfo
--
CREATE proc USP_InsertBillInfo
  (
	@IDBILL int,
	@IDFOOD int,
	@COUNT int
  )
 AS
 BEGIN
	declare @isExitBillnfo int;
	declare @foodCount int = 1;
	select @isExitBillnfo = ID , @foodCount = COUNT 
	from dbo.BILLINFO 
	where IDBILL = @IDBILL and IDFOOD = @IDFOOD
	if(@isExitBillnfo >0)
	BEGIN
		declare @newCount int = @foodCount + @COUNT
		IF(@newCount >0)
			update dbo.BILLINFO set COUNT = @foodCount + @COUNT
			where IDBILL = @IDBILL and IDFOOD = @IDFOOD
		else 
			DELETE dbo.BILLINFO where IDBILL = @IDBILL and IDFOOD = @IDFOOD
	END
	else
	BEGIN
		insert dbo.BILLINFO(IDBILL , IDFOOD , COUNT)
		values(@IDBILL  ,@IDFOOD , @COUNT)
	END
 END
GO



--
CREATE proc USP_UpdateAcc(
	@username nvarchar(50),
	@fullname nvarchar(50),
	@password varchar(50),
	@newpass varchar(50),
	@linkavt nvarchar(1000)
)
AS
BEGIN
	declare @passOK int =0
	select @passOK = count(*) from dbo.ACCOUNT where USERNAME = @username and PASSWORD = @password

	if(@passOK = 1)
	BEGIN
		if(@newpass = null or @newpass ='')
		BEGIN
			update dbo.ACCOUNT set FULLNAME = @fullname,AVT = @linkavt where USERNAME = @username and PASSWORD = @password
		END
		else
			update dbo.ACCOUNT set FULLNAME = @fullname, AVT = @linkavt, PASSWORD = @newpass where USERNAME = @username
	END
END
GO 



-- tạo thủ tục show food
CREATE PROC USP_GETFOOD_CATERRY_BYID(
	@IDCATERY INT
)
AS
BEGIN
	SELECT A.ID, A.NAME AS N'NAME', B.NAME AS N'CATERY', A.GIA as N'GIA'
	FROM DBO.FOOD A , DBO.FOODCATERY B
	WHERE A.IDCATERY = B.ID AND A.IDCATERY = @IDCATERY
END
GO

--
CREATE PROC USP_SHOWFOOD_CATERRY(
	@IDFOOD INT
)
AS
BEGIN
	SELECT A.ID, A.NAME AS N'NAME', B.NAME AS N'CATERY', A.GIA as N'GIA'
	FROM DBO.FOOD A , DBO.FOODCATERY B
	WHERE A.IDCATERY = B.ID
END
GO

-- 
alter trigger UTG_UPDATEBILLINFO
ON dbo.BILLINFO for insert, update
AS
BEGIN
	DECLARE @IDBILL int

	SELECT @IDBILL = IDBILL from inserted

	DECLARE @IDTABLE int

	SELECT @IDTABLE = IDTABLE from dbo.BILL where id= @IDBILL and status = 0

	DECLARE @COUNT INT
	SELECT @COUNT = COUNT(*) FROM DBO.BILLINFO WHERE IDBILL = @IDBILL

	IF(@COUNT>0)
		UPDATE dbo.TABLEfood set STATUS =N'Có Khách' where id = @IDTABLE
	ELSE
		UPDATE dbo.TABLEfood set STATUS =N'Trống' where id = @IDTABLE

END
GO

--
CREATE trigger UTG_UPDATEBILL
ON dbo.BILL for UPDATE
AS
BEGIN
	DECLARE @IDBILL int

	SELECT @IDBILL = ID from inserted

	DECLARE @IDTABLE int

	SELECT @IDTABLE = IDTABLE from dbo.BILL where ID = @IDBILL

	DECLARE @count int = 0

	SELECT @count = COUNT(*) from DBO.BILL where IDTABLE = @IDTABLE and STATUS = 0

	if(@count = 0)
		update dbo.TABLEfood set STATUS =N'Trống' where ID = @IDTABLE
END
GO


-- TẠO THỦ TỤC LẤY RA DS BILLINFO TỪNG BÀN
 ALTER PROC USP_SWITCHTABLE(
	@IDTABLE_1 INT,
	@IDTABLE_2 INT
 )
 AS
 BEGIN
	DECLARE @IDBILL_1 INT
	DECLARE @IDBILL_2 INT

	DECLARE @IS_TABLE_1_EMPTY INT = 1
	DECLARE @IS_TABLE_2_EMPTY INT = 1

	-- LẤY RA IDBILL CỦA 2 BÀN MÀ CẦN CHUYỂN BÀN CHO NHAU
	SELECT @IDBILL_2 = ID FROM BILL WHERE IDTABLE = @IDTABLE_2 AND STATUS = 0
	SELECT @IDBILL_1 = ID FROM BILL WHERE IDTABLE = @IDTABLE_1 AND STATUS = 0

	IF(@IDBILL_1 is NULL)
	BEGIN
		INSERT DBO.BILL(DATECHECKIN, DATECHECKOUT,IDTABLE,STATUS)
		VALUES(GETDATE(),NULL,@IDTABLE_1,0)

		SELECT @IDBILL_1 = MAX(ID) FROM BILL WHERE IDTABLE = @IDTABLE_1 AND STATUS = 0
		
		
	END

	SELECT @IS_TABLE_1_EMPTY = COUNT(*) FROM DBO.BILLINFO WHERE IDBILL = @IDBILL_1

	IF(@IDBILL_2 is NULL)
	BEGIN
		INSERT DBO.BILL(DATECHECKIN, DATECHECKOUT,IDTABLE,STATUS)
		VALUES(GETDATE(),NULL,@IDTABLE_2,0)
		
		SELECT @IDBILL_2 = MAX(ID) FROM BILL WHERE IDTABLE = @IDTABLE_2 AND STATUS = 0

	END

	SELECT @IS_TABLE_2_EMPTY = COUNT(*) FROM DBO.BILLINFO WHERE IDBILL = @IDBILL_2

	--
	SELECT ID INTO IDBILLINFO_TABLE FROM DBO.BILLINFO WHERE IDBILL = @IDBILL_2

	-- CHUYỂN HẾT BILLINFO TỪ BÀN 1 SANG CHO BÀN 2
	UPDATE BILLINFO SET IDBILL = @IDBILL_2 WHERE IDBILL = @IDBILL_1

	-- CHUYỂN HẾT BILLINFO TỪ BÀN 2 SANG CHO BÀN 1 VỚI ĐIỀU KIỆN
	UPDATE BILLINFO SET IDBILL = @IDBILL_1 WHERE ID IN (SELECT * FROM IDBILLINFO_TABLE)

	-- XÓA TABLE TỰ TẠO RA 
	DROP TABLE IDBILLINFO_TABLE

	IF(@IS_TABLE_1_EMPTY = 0)
		UPDATE DBO.TABLEfood SET STATUS = N'Trống'WHERE ID = @IDTABLE_2

	IF(@IS_TABLE_2_EMPTY = 0)
		UPDATE DBO.TABLEfood SET STATUS = N'Trống'WHERE ID = @IDTABLE_1
 END
 GO

 -- 
 ALTER TABLE BILL ADD TONGTIEN_HOADON FLOAT DEFAULT 0
 GO
 ALTER TABLE BILL ADD TONGTIEN_THANHTOAN FLOAT DEFAULT 0
 GO
 --

 -- 
 CREATE PROC USP_GETLISTBILLBYDATE
 (
	@datecheckin datetime,
	@datecheckout datetime
 )

 AS
 BEGIN
	SELECT T.NAME, B.TONGTIEN_HOADON, B.TONGTIEN_THANHTOAN, B.GIAMGIA, B.DATECHECKIN, B.DATECHECKOUT
	FROM BILL AS B, TABLEfood AS T
	WHERE DATECHECKIN >= @datecheckin AND DATECHECKOUT <= @datecheckout AND B.STATUS =1 AND B.IDTABLE = T.ID 
 END
 GO


 --
 CREATE PROC USP_GETNUMBERBILL
 (
	@datecheckin datetime,
	@datecheckout datetime
 )

 AS
 BEGIN
	SELECT COUNT(*)
	FROM BILL AS B, TABLEfood AS T
	WHERE DATECHECKIN >= @datecheckin AND DATECHECKOUT <= @datecheckout AND B.STATUS =1 AND B.IDTABLE = T.ID 
 END
GO

---

alter PROC USP_TotalPrice_HD(
	@datecheckin datetime,
	@datecheckout datetime
)
AS 
BEGIN 
	
	SELECT SUM(TONGTIEN_HOADON) FROM BILL AS B
	--WHERE DATECHECKIN >= '20180506 00:00:00.000' AND DATECHECKOUT <= '20180509 00:00:00.000' AND B.STATUS =1
	WHERE DATECHECKIN >= @datecheckin AND DATECHECKOUT <= @datecheckout AND B.STATUS =1
END
GO

--
CREATE PROC USP_TotalPrice_TT(
	@datecheckin datetime,
	@datecheckout datetime
)
AS 
BEGIN 
	SELECT SUM(TONGTIEN_THANHTOAN) FROM BILL
	WHERE DATECHECKIN >= @datecheckin AND DATECHECKOUT <= @datecheckout AND B.STATUS =1
END
GO

---
create view VW_show
as

 SELECT  BILLINFO.COUNT,FOOD.NAME, BILLINFO.COUNT*FOOD.GIA as N'THANHTIEN'
	FROM (DBO.FOOD INNER JOIN BILLINFO 
	ON FOOD.ID = BILLINFO.IDFOOD) inner join BILL
	ON BILLINFO.IDBILL = BILL.ID and bill.STATUS = 0 INNER JOIN TABLEfood
	ON TABLEfood.ID = BILL.IDTABLE and TABLEfood.ID =1








